version: '3'
services:
  docker-factorio:
    build: .
    container_name: docker-factorio
    restart: always
    volumes:
      - ../volumes/factorio/saved-games:/app/saves
      - ../volumes/factorio/last-game/last-game.txt:/app/last-game.txt
    networks:
      - container-network
networks:
  container-network:
    external: true