version: '3'
services:
  docker-factorio:
    build: .
    container_name: docker-factorio
    restart: always
    networks:
      - container-network
networks:
  container-network:
    external: true